name: CI - Streamlit App

on:
  push:
    branches: [  ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov selenium webdriver-manager

      - name: Lint check
        run: |
          pip install flake8
          flake8 app/ --max-line-length=120 --ignore=E402
          
      - name: Run unit tests
        run: |
          pytest tests/unit/ -v

      - name: Set up Chrome for Selenium tests
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Run e2e tests
        run: |
          # Start Streamlit in background
          streamlit run app/Home.py --server.headless true &
          # Wait for Streamlit to start
          sleep 10
          # Run e2e tests
          pytest tests/e2e/ -v

      - name: Basic Streamlit run check
        run: |
          # Kill any running Streamlit instance
          pkill -f streamlit || true
          # Start fresh instance
          streamlit run app/Home.py --server.headless true &
          sleep 10 
