name: CI - Streamlit App

on:
  push:
    branches: [  ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov selenium webdriver-manager flake8 requests

      - name: Confirm Dictionary.py file (case sensitive)
        run: |
          echo "📄 Listing files in pages/"
          ls -l app/pages

      - name: Lint check
        run: |
          flake8 app/ --max-line-length=120

      - name: Run unit tests
        run: |
          pytest tests/unit/ -v

      - name: Set up Chrome for Selenium tests
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Run E2E tests with Streamlit
        run: |
          echo "🚀 Starting Streamlit..."
          streamlit run app/Home.py --server.headless true &
          
          echo "⏳ Waiting for Streamlit to become responsive..."
          for i in {1..60}; do
            if curl -s http://localhost:8501/Dictionary | grep -q "Manage Coding Dictionary"; then
              echo "✅ Streamlit is ready"
              break
            fi
            echo "Waiting ($i)..."
            sleep 1
          done

          echo "🔎 Running E2E tests"
          pytest tests/e2e/ -v

      - name: Kill Streamlit after tests
        if: always()
        run: |
          pkill -f streamlit || true
