name: PlanB CI

on:
  push:
    branches: [ main ]
    paths:
      - 'planb/**'
      - 'tests/planb/**'
      - 'planb/requirements-planb.txt'
      - '.github/workflows/planb-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'planb/**'
      - 'tests/planb/**'
      - 'planb/requirements-planb.txt'
      - '.github/workflows/planb-ci.yml'

jobs:
  test:
    name: Run PlanB Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r planb/requirements-planb.txt
          pip install pytest

      - name: Run PlanB tests
        run: |
          pytest -q tests/planb

      - name: Report test results
        if: always()
        run: |
          echo "PlanB test run completed" 